services:
  db:
    container_name: '${DOCKER_CONTAINER_NAME_DB}'
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
     FLASK_APP: main.py
     FLASK_RUN_HOST: 0.0.0.0
     FLASK_RUN_PORT: 5000
     POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'
     POSTGRES_USER: '${DATABASE_USER}'
     POSTGRES_DB: '${DATABASE_NAME}'
  web:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: '${DATABASE_URL}'
      JWT_SECRET_KEY: '${JWT_SECRET_KEY}'
    ports:
      - "5000:5000"