services:
  db:
    container_name: '${DOCKER_CONTAINER_NAME_DB}'
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'
      POSTGRES_USER: '${DATABASE_USER}'
      POSTGRES_DB: '${DATABASE_NAME}'
